config/routes.rb
Rails.application.routes.draw do
  get "search" => "searches#search"
  get 'favorit1es/create'
  get 'favorit1es/destroy'
  get 'favorites/create'
  get 'favorites/destroy'
  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about", as: 'about'

  resources :books, only: [:new, :create, :index, :show, :update, :edit, :destroy] do 
    resources :book_comments, only: [:create, :destroy]
    resource :favorit1es, only: [:create, :destroy]
  end 
  
  resources :users, only: [:show, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
  resources :chats, only: [:show, :create]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
  
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, length: { in: 1..200 }

  has_one_attached :image
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorit1es, dependent: :destroy
  has_many :favirit1ed_users, through: :favorit1es, source: :user
  
  has_many :view_counts, dependent: :destroy
  
  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) } 
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) } 
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  
  def favorited_by?(user)
    favorit1es.exists?(user_id: user.id)
  end
  
  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  validates :comment, presence: true
    
  belongs_to :user
  belongs_to :book
  
end

app/models/chat.rb
class Chat < ApplicationRecord
    
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }
  
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorit1e.rb
class Favorit1e < ApplicationRecord
    
  belongs_to :user
  belongs_to :book
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    
  belongs_to :user
  belongs_to :book
  
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
end

app/models/room.rb
class Room < ApplicationRecord
    
  has_many :user_rooms
  has_many :chats
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, length: { in: 2..20 },
                   uniqueness: true 
  validates :introduction, length: {maximum: 50 }
  
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  
  has_many :view_counts, dependent: :destroy

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorit1es, dependent: :destroy
  has_many :favirit1ed_users, through: :favorit1es, source: :book

  has_one_attached :profile_image
  
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  def get_profile_image(width, height)
    unless profile_image.attached?
       file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
def follow(user_id)
  relationships.create(followed_id: user_id)
end

def unfollow(user_id)
  relationships.find_by(followed_id: user_id).destroy
end

def following?(user)
  followings.include?(user)
end

# 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

end 

app/models/user_room.rb
class UserRoom < ApplicationRecord
    
  belongs_to :user
  belongs_to :room
  
end

app/models/view_coun1t.rb
class ViewCoun1t < ApplicationRecord
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :ensure_current_user, {only: [:edit, :update]}

  def index
    @users = User.all
    @books = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page])
    @book = Book.new
    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
  end

  def edit
    @user = User.find(params[:id])  
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
      flash[:notice] = "You have updated user successfully."
    else
      render :edit
    end
  end



  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
def ensure_current_user
  if current_user.id != params[:id].to_i
    redirect_to user_path(current_user.id)
  end
end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorit1es_helper.rb
module Favorit1esHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<p><%= image_tag user.get_profile_image(100,100) %></p>
<table class='table'>
  
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  
   <tr>
          <th>follows</th>
          <th><%= link_to user.followings.count,user_followings_path(user.id)  %></th>
          </tr>
          <tr>
          <th>follower</th>
          <th><%= link_to user.followers.count,user_followers_path(user.id) %></th>
        </tr>
  
</table>


<div>
<% if user != current_user %>
  <% if current_user.following?(user) %>
    <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
  <% end %>
<% end %>

<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>
</div>

　

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>件のエラーが発生しました
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="containar">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-1 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
<%= form_with model: @user do |f| %>
  <div class="form-group">
  <label for="inputName">Name</label>
  <p><%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"Name"%></p>
  </div>

  <div class="form-group">
  <label for="inputImage">Image</label>
  <p><%= f.file_field :profile_image, placeholder: "Image", accept: "image/*" %></p>
  </div>

  <div class="form-group">
  <label for="inputIntroduction">Introduction</label>
  <p><%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:"Introduction" %></p>
  </div>

  <div class="form-group">
      <%= f.submit "Update User",class: 'btn btn-secondary' do%>
      <% end %>
  </div>
<% end %>


    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">

  <div class="row">
    <div class="col-md-3">

<%= render 'user', user: current_user %>
<%= render 'books/new', book: @books %>

</div>

      <div class="col-md-8 offset-md-1">
<h1>Users</h1>

<table class="table">
  <tr>
   <th>Image</th>
   <th>Name</th>
   <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
   <th>
     <span>
      <p><%= image_tag user.get_profile_image(100,100) %></p>
     </span>
   </th>
   <th>
     <span>
      <p><%= user.name %></p>
     </span>
   </th>

          <th>フォロー数: <%= user.followings.count %></th>
          
          <th>フォロワー数: <%= user.followers.count %></th>
   
   <th>
       <% if user != current_user %>
         <% if current_user.following?(user) %>
           <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
         <% else %>
           <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
         <% end %>
       <% end %>
   </th>
   
   <th>
     <% if current_user != user && current_user.following?(user) && user.following?(current_user) %>
       <%= link_to 'chatを始める', chat_path(user.id), class: "ml-3" %>
     <% end %>
   </th>

   <th>
     <span>
      <p> <%= link_to "Show", user_path(user.id) %></p>
     </span>
   </th>
  </tr>
  <% end %>
</table>
    </div>
  </div>

</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">

  <div class="row">
    <div class="col-md-3">
      <%= render 'user', user: @user %>
      <%= render 'books/new', book: @book %>
    </div>


      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>

<table class="table">
  <tr>
    <th></th>
   <th>Title</th>
   <th>Opinion</th>
  </tr>

  <% @books.each do |book| %>
  <tr>
   <th>
     <span>
        <%= link_to user_path(book.user.id),class: 'nav-link text-blue' do %>
        <%= image_tag book.user.get_profile_image(100,100) %><br>
        <% end %>
     </span>
   </th>
   <th>
     <span>
      <p><%= link_to book.title, book_path(book.id) %></p>
     </span>
   </th>

   <th>
     <span>
      <p><%= book.body %></p>
     </span>
   </th>
   
  </tr>
  <% end %>
</table>

 <div class = "table_width">
   <table class="table table-bordered">
    <thead>
     <tr>
      <th>今日の投稿数</th>
      <th>前日の投稿数</th>
      <th>前日比</th>
     </tr>
    </thead>
    <tbody>
     <tr>
     　<td><%= @today_book.count %></td>
     　<td><%= @yesterday_book.count %></td>
     　<td>
       <% if @yesterday_book.count == 0 %>
        前日の投稿はありません
       <% else %>
       　<% @the_day_before =   @today_book.count / @yesterday_book.count.to_f  %>
       　<%= (@the_day_before * 100).round %>
       <% end %>
      </td>
     </tr>
    </tbody>
   </table>
   
   
   <table class="table">
  <thead>
  <tr>
   <th>今週の投稿</th>
   <th>先週の投稿</th>
   <th>先週比</th>
  </tr>
  </thead>
   <tbody>
    <tr>
     <td><%= @this_week_book.count %></td>
     <td><%= @last_week_book.count %></td>
     <% if @last_week_book.count == 0 %>
     <td>先週の投稿はなし</td>
     <% else %>
       　<td><% @the_week_before =   @this_week_book.count / @last_week_book.count.to_f  %>
       　<%= (@the_week_before * 100).round %>%</td>
     <% end %>
     </tr>
   </tbody>
  </table>
   
  </div>


    </div>
  </div>

</div>