config/routes.rb
Rails.application.routes.draw do
  get "search" => "searches#search"
  get 'favorit1es/create'
  get 'favorit1es/destroy'
  get 'favorites/create'
  get 'favorites/destroy'
  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about", as: 'about'

  resources :books, only: [:new, :create, :index, :show, :update, :edit, :destroy] do 
    resources :book_comments, only: [:create, :destroy]
    resource :favorit1es, only: [:create, :destroy]
  end 
  
  resources :users, only: [:show, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
  resources :chats, only: [:show, :create]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
  
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, length: { in: 1..200 }

  has_one_attached :image
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorit1es, dependent: :destroy
  has_many :favirit1ed_users, through: :favorit1es, source: :user
  
  has_many :view_counts, dependent: :destroy
  
  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) } 
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) } 
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  
  def favorited_by?(user)
    favorit1es.exists?(user_id: user.id)
  end
  
  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  validates :comment, presence: true
    
  belongs_to :user
  belongs_to :book
  
end

app/models/chat.rb
class Chat < ApplicationRecord
    
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }
  
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorit1e.rb
class Favorit1e < ApplicationRecord
    
  belongs_to :user
  belongs_to :book
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    
  belongs_to :user
  belongs_to :book
  
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
end

app/models/room.rb
class Room < ApplicationRecord
    
  has_many :user_rooms
  has_many :chats
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, length: { in: 2..20 },
                   uniqueness: true 
  validates :introduction, length: {maximum: 50 }
  
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  
  has_many :view_counts, dependent: :destroy

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorit1es, dependent: :destroy
  has_many :favirit1ed_users, through: :favorit1es, source: :book

  has_one_attached :profile_image
  
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  def get_profile_image(width, height)
    unless profile_image.attached?
       file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
def follow(user_id)
  relationships.create(followed_id: user_id)
end

def unfollow(user_id)
  relationships.find_by(followed_id: user_id).destroy
end

def following?(user)
  followings.include?(user)
end

# 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

end 

app/models/user_room.rb
class UserRoom < ApplicationRecord
    
  belongs_to :user
  belongs_to :room
  
end

app/models/view_coun1t.rb
class ViewCoun1t < ApplicationRecord
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :ensure_current_book, {only: [:edit, :update]}

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @book_page = Book.page(params[:page])
    @book = Book.new
    @books = Book.includes(:favirit1ed_users).sort {|a,b| b.favirit1ed_users.size <=> a.favirit1ed_users.size}
  end

  def show
    @books = Book.new
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
    @book_comments = @book.book_comments
    @book_detail = Book.find(params[:id])
    unless ViewCount.find_by(user_id: current_user.id, book_id: @book_detail.id)
      current_user.view_counts.create(book_id: @book_detail.id)
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def ensure_current_book
   @book = Book.find(params[:id])
   if current_user.id != @book.user_id
     redirect_to books_path
   end
  end 
  
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorit1es_helper.rb
module Favorit1esHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_new.html.erb
<h2 class="mt-3">New book</h2>

  <%= form_with model: book do |f| %>
    <div class="form-group">Title</div>
      <%= f.text_field :title %>
    <div class="form-group">Opinion</div>
      <%= f.text_area :body %>
    <div class="form-group">
      <%= f.submit "Create Book",class: 'btn btn-success' do%>
      <% end %>
    </div>
  <% end %>

app/views/books/edit.html.erb
<div class="container">
<div class="row">
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">


<h2>Editing Book</h2>

<% if @book.errors.any? %>
  <%= @book.errors.count %> error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book do |f| %>

<p>Title</p>
<p><%= f.text_field :title %></p>
<P>Opinion</p>
<p><%= f.text_area :body %></p>
<div class="form-group">
      <%= f.submit "Update Book",class: 'btn btn-success' do%>
      <% end %>
</div>

<% end %>
<%= link_to "Show", book_path(@book.id) %>
|
<%= link_to "Back", books_path %>
</div>
</div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">

<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<%= render 'users/user', user: current_user %>
<%= render 'new', book: @book %>
</div>

      <div class="col-md-8 offset-md-1">

<h1>Books</h1>

<table class="table">
  <tr>
   <th></th>
   <th>Title</th>
   <th>Opinion</th>
  </tr>

<% @books.each do |book| %>
  <tr>
   <th>

     <span>
        <%= link_to user_path(book.user.id),class: 'nav-link text-blue' do %>
        <%= image_tag book.user.get_profile_image(100,100) %>
        <% end %>
     </span>
     
   </th>
   <th>
     <span>
      <p><%= link_to book.title, book_path(book.id) %></p>
     </span>
   </th>

   <th>
     <span>
      <p> <%= book.body %></p>
     </span>
   </th>
   
   <th>
       <p>コメント件数：<%= book.book_comments.count %></p>
   </th>
   
   <th id="favorite_buttons_<%= book.id %>">
       <%= render "favorit1es/favorit1es", book: book %>
       
   </th>
      <% end %>
  </tr>
</table>
    </div>
  </div>

</div>

app/views/books/new.html.erb
<%= render 'new', book: @book %>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">

  <div class="row">
    <div class="col-md-3">

<% if @book.user_id == current_user.id %>
      <%= render 'users/user', user: current_user %>
      <% else %>
      <%= render 'users/user', user: @book.user %>
<% end %>
<%= render 'new', book: @books %>
</div>

      <div class="col-md-8 offset-md-1">

<h2>Book detail</h2>


<table class="table">

  <tr>
   <th>
     <span>
        <%= link_to user_path(@book.user.id),class: 'nav-link text-blue' do %>
        <%= image_tag @book.user.get_profile_image(100,100) %><br>
        <%= @book.user.name %>
        <% end %>
     </span>
   </th>



   <th>
     <span>
      <p><%= link_to @book.title, book_path(@book.id) %></p>
     </span>
   </th>

   <th>
     <span>
      <p><%= @book.body %></p>
     </span>
   </th>

   <% if @book.user_id == current_user.id %>
   <th>
         <%= link_to edit_book_path(@book.id),class: "btn btn-sm btn-success edit_book_210" do %>
         Edit
         <% end %>
   </th>

   <th>
         <%= link_to book_path(@book.id), method: :delete,"data-confirm" => "本当に削除しますか？", class: "btn btn-sm btn-danger destroy_book_210" do %>
         Destroy
         <% end %>
   </th>
   <% end %>
   
<th>
    <div>
  <p>コメント件数：<%= @book.book_comments.count %></p>
  <% @book.book_comments.each do |book_comment| %>
    <p><%= image_tag book_comment.user.get_profile_image(100,100) %></p>
    <%= book_comment.user.name %>
    <%= book_comment.created_at.strftime('%Y/%m/%d') %><%= book_comment.comment %>
    <% if book_comment.user == current_user %>
      <%= link_to "削除", book_book_comment_path(book_comment.book, book_comment), method: :delete %>
    <% end %>
  <% end %>


</th>

   
   <th>

<div>
  <%= form_with model: [@book, @book_comment] do |f| %>
    <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
    <%= f.submit "送信する" %>
  <% end %>
</div>
   </th>
   
   <th>
       <% if @book.favorited_by?(current_user) %>
    <p>
      <%= link_to book_favorit1es_path(@book), method: :delete do %>
        ♥<%= @book.favorit1es.count %> いいね
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to book_favorit1es_path(@book), method: :post do %>
        ♡<%= @book.favorit1es.count %> いいね
      <% end %>
    </p>
  <% end %>
   </th>
   
   <th><p class="view-count">👀数: <%= @book_detail.view_counts.count %></p></th>
   
  </tr>
</table>
    </div>
  </div>
</div>