config/routes.rb
Rails.application.routes.draw do
  get "search" => "searches#search"
  get 'favorit1es/create'
  get 'favorit1es/destroy'
  get 'favorites/create'
  get 'favorites/destroy'
  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about", as: 'about'

  resources :books, only: [:new, :create, :index, :show, :update, :edit, :destroy] do 
    resources :book_comments, only: [:create, :destroy]
    resource :favorit1es, only: [:create, :destroy]
  end 
  
  resources :users, only: [:show, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
  resources :chats, only: [:show, :create]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
  
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, length: { in: 1..200 }

  has_one_attached :image
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorit1es, dependent: :destroy
  has_many :favirit1ed_users, through: :favorit1es, source: :user
  
  has_many :view_counts, dependent: :destroy
  
  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) } 
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) } 
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  
  def favorited_by?(user)
    favorit1es.exists?(user_id: user.id)
  end
  
  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  validates :comment, presence: true
    
  belongs_to :user
  belongs_to :book
  
end

app/models/chat.rb
class Chat < ApplicationRecord
    
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }
  
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorit1e.rb
class Favorit1e < ApplicationRecord
    
  belongs_to :user
  belongs_to :book
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    
  belongs_to :user
  belongs_to :book
  
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
end

app/models/room.rb
class Room < ApplicationRecord
    
  has_many :user_rooms
  has_many :chats
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, length: { in: 2..20 },
                   uniqueness: true 
  validates :introduction, length: {maximum: 50 }
  
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  
  has_many :view_counts, dependent: :destroy

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorit1es, dependent: :destroy
  has_many :favirit1ed_users, through: :favorit1es, source: :book

  has_one_attached :profile_image
  
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  def get_profile_image(width, height)
    unless profile_image.attached?
       file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
def follow(user_id)
  relationships.create(followed_id: user_id)
end

def unfollow(user_id)
  relationships.find_by(followed_id: user_id).destroy
end

def following?(user)
  followings.include?(user)
end

# 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

end 

app/models/user_room.rb
class UserRoom < ApplicationRecord
    
  belongs_to :user
  belongs_to :room
  
end

app/models/view_coun1t.rb
class ViewCoun1t < ApplicationRecord
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/42e9d4206e.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

            <% if user_signed_in? %>
             <li>
              <%= link_to user_path(current_user),class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> Home
              <% end %>
             </li>

             <li>
              <%= link_to '/users',class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i> Users
              <% end %>
             </li>

             <li>
              <%= link_to '/books',class: 'nav-link text-light' do %>
              <i class="fas fa-book-open"></i> Books
              <% end %>
             </li>

             <li>
              <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i> Log out
              <% end %>
             </li>


            <% else %>
             <li>
              <%= link_to '/',class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> Home
              <% end %>
             </li>

             <li>
              <%= link_to about_path,class: 'nav-link text-light' do %>
              <i class="fas fa-link"></i> About
              <% end %>
             </li>

             <li>
              <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"></i> Sign up
              <% end %>
             </li>

             <li>
              <%= link_to new_user_session_path,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i> Log in
              <% end %>
             </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
  </header>

  <%= flash[:notice] %>
  
  <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
  <% if user_signed_in? %>
  <div class="search_form">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['User'], ['Book']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>
</div>
</div>
</div>

    <%= yield %>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>